<?xml version="1.0"?>
<package format="2">
  <name>mic_msg</name>
  <version>0.1.0</version>
  <description>Microphone message definitions for voice assistant</description>

  <maintainer email="rm@todo.todo">rm</maintainer>

  <license>MIT</license>

  <url type="website">http://wiki.ros.org/mic_msg</url>

  <author email="rm@todo.todo">RM</author>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>message_generation</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_export_depend>std_msgs</build_export_depend>
  <exec_depend>message_runtime</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>
    <!-- Other tools can request additional information be placed here -->
  </export>
</package>
